### ISSUE TITLE
Lack of Automated Interfaces for CCPA

### ISSUE THREAD

**Issue by blackstar257** [caprivacy/caprivacy#12]
Is this supposed to be a list with only automated api/forms for submissions around CCPA? I keep running into companies that don't have automated forms/APIs but just text saying email or mail letters.

**Comment by blackstar257** [comment]
Example
https://www.grubhub.com/legal/ca-privacy-notice

**Comment by blackstar257** [comment]
```
Unless you have exercised your Right to Opt-out, we may disclose or “sell” your personal information to third parties for monetary or other valuable consideration. The third parties to whom we sell personal information may use such information for their own purposes in accordance with their own privacy policies. Remember, CCPA defines data “sales” broadly. While Grubhub may disclose or otherwise share your personal information with select third parties, we do not sell your data to third parties in the traditional sense of the word, including collecting, compiling and then selling your data to data brokers, data resellers or other similar parties.

To exercise the Right to Opt-out of personal information sales, you may submit a request below:

For Grubhub, click here.
For Seamless, click here.
```

They have this on their page but it doesnt actually link anywhere.

**Comment by blackstar257** [comment]
For now ill just submit ones with forms

**Comment by caprivacy** [comment]
In here I'd like to link to the closest form or ccpa page specifically. Maybe eventually it can be changed to have links to companies out of compliance without ccpa sections.

**Comment by blackstar257** [comment]
Maybe a separate list for companies that DO NOT have an automated system setup?

https://www.lowes.com/l/privacy-and-security-statement.html#MoreAboutSale

**Comment by WaveBirdDash** [comment]
Maybe that could be a separate page, listing companies that don’t have simple links to forms.

**Comment by liamengland1** [comment]
Another question, should the "do not sell" form and "right to know/delete" form be listed separately? On some sites (example acxiom, see my PR) they are two different pages. Which is preferable?

**Comment by blackstar257** [comment]
https://github.com/caprivacy/caprivacy/pull/40 Doing something template based on this would make this easy.
