### ISSUE TITLE
Enable GitHub Pages

### ISSUE THREAD

**Issue by farktronix** [caprivacy/caprivacy#4]
Enabling Github pages makes for a slightly nicer looking web page for the non-technically inclined. I enabled it [on my fork](https://farktronix.github.io/caprivacy/) along with the ```slate``` theme.

You can enable Github pages by going [here](https://github.com/caprivacy/caprivacy/settings) and scrolling down to the "GitHub Pages" section. Enable "master branch" as the source, then click "change theme"- I recommend the "Slate" theme.

After that the page should be available [here](https://caprivacy.github.io/caprivacy/) and I would recommend sharing that link with everyone instead of the direct link to index.md

**Comment by caprivacy** [comment]
Thanks just updated it and also updated the caprivacy.me link to point to the GitHub pages! I've been looking for more links than formatting so this helps a lot!

**Comment by farktronix** [comment]
Looks great!
