### ISSUE TITLE
Webapp to automate CCPA submissions?

### ISSUE THREAD

**Issue by laudiacay** [caprivacy/caprivacy#5]
Hey, I'm interested in chatting about building a webapp that can automate the CCPA deletion process. The app would prompt users and guide them through uploading the data they need to submit in order to get stuff deleted or not shared, then it would automatically click through all the forms and submit requests on all the sites depending on what the user is eligible for/has input data for. The interface could be something between the interface of unroll.me and Lastpass's automatic password reset functionality. It would not use people's data sketchily, would have minimal permissions to any accounts of theirs it needed to log into, and we'd make it super easy for people to delete their stuff from our systems (or even autodelete after some time!). I'm thinking I'd use Django or Flask (maybe running in an AWS lambda via Zappa?) for most of it, then AWS lambdas for the CCPA submission jobs. 

This git repo would be really useful info for building the CCPA submission jobs. I am looking for more people who might be interested in helping build it- specifically frontend devs and a TON of people who could write the code to submit CCPA requests. It'd also be cool to get AWS resources so that this is scalable and easy to secure, as opposed to running this on my desktop. Finally, I'm reaching out through this Github issue because I'm just a college kid with no clout, and I know you run CPV and probably have EFF friends, so potentially you signal boosting or helping me get one of these organizations affiliated with this app would make the app more trustworthy to people worried about their data and also make more people likely to use it.

I'd like to make this free, so that it's accessible to nontechnical and busy people. I also want to make the whole thing (down to infrastructure as code) open sourced so that more people can contribute and so that people can be confident that their data is protected. I'd also want to open-source some code to programatically submit the CCPA takedowns yourself, because some people won't want to hand over their data.

Anyway, let me know what you think, or if you could point me towards the resources I mentioned earlier!

**Comment by blackstar257** [comment]
Im down!

**Comment by laudiacay** [comment]
if you're interested in this, HMU on twitter @\_\_laudecay\_\_, i'll make a GC soon so that people can coordinate. my friend and i are starting development probably tmrw night!

**Comment by caprivacy** [comment]
I'm in for this too but be advised that while they can be automated, companies are requesting validation of users. Meaning, only Californians can submit these DSARs. 

Any automated system must start by validating the user is a Californian resident

**Comment by laudiacay** [comment]
not necessarily, i know some companies (i heard microsoft?) have opened this up to any american or even any customer. 

we could just have a list of companies and a list of documentation/info/requirements that companies would need, and then the site could have sort of a list of all the companies we support and a way to filter by what documentation the current user would need to upload in order to submit a takedown to those companies, and a way to track which takedowns have already been submitted/processed. I know my company is asking for a notarized statement that someone's a CA resident, so my company's name would be greyed out until the user uploaded that statement as a PDF.

**Comment by caprivacy** [comment]
Yea I think we'll have to go through these links and grid out as v2 the level of compliance with each right and whether they've opened it up to everyone or just CA residents.

**Comment by dmarti** [comment]
Here's a link to a related project. "This website makes it easy to get organizations to erase your data by automating the process of sending GDPR and CCPA erasure (right to be forgotten) requests."

https://github.com/opt-out-eu/yourdigitalrights.org

**Comment by blackstar257** [comment]
yourdigitalrights.org is nice but it seems to be focused on just crafting you an email with prefabbed text.
We might benefit from combining our efforts. 

https://api.opt-out.eu/companies

**Comment by Bilal-S** [comment]
You could signup for a free XcooBee account and manage all your GDPR and CCPA erasure request as well as Supervisory Authority complaints from one place. 

https://www.xcoobee.com

In addition XcooBee has free/open source tools for organization to use for Cookie Management, Fingerprinting and Do-Not-Sell management.

https://github.com/XcooBee/xcoobee-cookie-kit/tree/master/packages/xcoobee-cookie-kit-web
