### ISSUE TITLE
ci build

### ISSUE THREAD

**Issue by damianFC** [caprivacy/caprivacy#52]
Been looking at the reasons for the build failure and it seems the linter needs to have LazyQuotes enabled:

https://github.com/golang/go/issues/21672

I think we'll definitely have to use names like Kohl's and the like that have single quotes inside double quotes. 

Please take a look!

**Comment by blackstar257** [comment]
Updated my action to support lazyquotes by default with option to disable if needed.

https://github.com/caprivacy/caprivacy/runs/373461301#step:4:16

**Comment by blackstar257** [comment]
https://github.com/caprivacy/caprivacy/pull/55

**Comment by damianFC** [comment]
This is awesome thank you so much.

I created a new Project to tackle any API & Automation for the repo stories. I think other than a CSV Linter we might want to also have a sorter too to make sure they're sorted alphabetically. :)

**Comment by blackstar257** [comment]
Closing this since the bug was fixed. The sorting I will add to the project todo
